<!doctype html>
<html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>چاپ انتخاب رشته</title><style>
body{font-family:Tahoma,Arial,sans-serif;color:#111;margin:18mm;font-size:12px}.head{border-bottom:2px solid #222;padding-bottom:8px;margin-bottom:12px}.title{font-size:18px;font-weight:700}.meta{display:grid;grid-template-columns:repeat(2,1fr);gap:6px;margin-bottom:12px}.columns{display:grid;grid-template-columns:1fr 1fr;gap:12px;direction:rtl}.column{border:1px solid #333}.row{display:grid;grid-template-columns:30px 75px 1fr 90px;border-bottom:1px solid #bbb;min-height:25px}.row:last-child{border-bottom:0}.row>*{padding:5px;border-left:1px solid #bbb}.row>*:last-child{border-left:0}.header{font-weight:700;background:#eee}@page{size:A4;margin:12mm}@media print{body{margin:0}.no-print{display:none}}
</style></head><body>
<div class="head"><div class="title">{{ app(\App\Services\SettingsService::class)->get('institute_name', config('app.name')) }}</div><div>لیست انتخاب رشته | نسخه {{ \App\Support\PersianDate::number($plan->version) }}</div></div>
<div class="meta"><div>دانش‌آموز: {{ $plan->student?->full_name ?: '-' }}</div><div>رشته: {{ $plan->student?->major ?: '-' }}</div><div>نوع کنکور: {{ $plan->student?->examTypeLabel() ?: '-' }}</div><div>تراز/رتبه: {{ $plan->student?->score ?: '-' }}</div><div>زمان رزرو: {{ \App\Support\PersianDate::date($plan->reservation?->slot?->date) }} - {{ \App\Support\PersianDate::time($plan->reservation?->assignedStartTime()) }}</div><div>تاریخ انتشار: {{ \App\Support\PersianDate::dateTime($plan->published_at ?: $plan->created_at) }}</div></div>
<div class="columns">@foreach([$plan->items->take(75), $plan->items->slice(75)] as $items)<div class="column"><div class="row header"><div>ردیف</div><div>کد رشته</div><div>نام رشته</div><div>شهر</div></div>@foreach($items as $item)<div class="row"><div>{{ \App\Support\PersianDate::number($item->priority_order) }}</div><div>{{ $item->field_code }}</div><div>{{ $item->field_name }}</div><div>{{ $item->city }}</div></div>@endforeach</div>@endforeach</div>
<script>window.addEventListener('load', function(){ window.print(); });</script>
</body></html>
