@extends('layouts.admin')

@section('title', 'آمار انتخاب رشته اپراتورها')
@section('subtitle', 'عملکرد اپراتورها در ایجاد و ویرایش انتخاب رشته‌ها')

@section('content')
    <div class="card filter-card mb-4"><div class="card-body"><form class="row g-3"><div class="col-md-3"><label class="form-label">از تاریخ</label><input name="from" value="{{ \App\Support\PersianDate::inputDate($filters['from'] ?? null) }}" class="form-control jalali-date-picker" autocomplete="off"></div><div class="col-md-3"><label class="form-label">تا تاریخ</label><input name="to" value="{{ \App\Support\PersianDate::inputDate($filters['to'] ?? null) }}" class="form-control jalali-date-picker" autocomplete="off"></div><div class="col-md-3"><label class="form-label">اپراتور</label><select name="operator_id" class="form-select"><option value="">همه</option>@foreach($summary as $stat)<option value="{{ $stat['operator_id'] }}" @selected(($filters['operator_id'] ?? null) == $stat['operator_id'])>{{ $stat['operator_name'] }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">نوع فعالیت</label><select name="activity_type" class="form-select"><option value="">همه</option><option value="created" @selected(($filters['activity_type'] ?? null) === 'created')>ایجاد شده</option><option value="edited" @selected(($filters['activity_type'] ?? null) === 'edited')>ویرایش شده</option></select></div><div class="col-12 d-flex gap-2"><button class="btn btn-primary">اعمال فیلتر</button><a href="{{ route('admin.reports.operator-field-selection.index') }}" class="btn btn-outline-secondary">پاک کردن فیلترها</a></div></form></div></div>

    <div class="card"><div class="card-header"><i class="ri-bar-chart-box-line align-middle text-muted me-1"></i> آمار انتخاب رشته اپراتورها</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>اپراتور / مشاور</th><th>تعداد ایجاد انتخاب رشته</th><th>تعداد ویرایش انتخاب رشته</th><th>آخرین فعالیت</th><th>جزئیات</th></tr></thead><tbody>@forelse($summary as $stat)<tr><td>{{ $stat['operator_name'] }}</td><td>{{ \App\Support\PersianDate::number($stat['created_plans_count']) }}</td><td>{{ \App\Support\PersianDate::number($stat['edit_actions_count']) }}</td><td>{{ \App\Support\PersianDate::dateTime($stat['last_activity_at']) }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.reports.operator-field-selection.show', array_filter(['operator' => $stat['operator_id'], ...$filters])) }}">مشاهده جزئیات</a></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">هنوز فعالیتی برای انتخاب رشته ثبت نشده است.</td></tr>@endforelse</tbody></table></div></div>
@endsection
